version: "3.7"
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  frontend_container:
    build: ./Mortage-Planner-FrontEnd
    ports:
      - 8081:8080
  backend_container:
    build: ./Mortage-Planner-Backend
    ports:
      - 8080:8080
    depends_on:
      - mongodb_container
    command: ["./wait-for-it.sh"]
volumes:
  mongodb_data_container:
